name: Deploy Site

on:
  push:
    branches: [main]
  workflow_dispatch: # Permite rodar manualmente se precisar

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install and Build
        run: |
          npm install
          npm install --save-dev typescript @types/react @types/node @types/react-dom
          npx next build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # O Next.js gera a exportação estática aqui

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
