name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # As linhas abaixo ignoram erros de TypeScript e Lint durante o build
      NEXT_PUBLIC_IGNORE_TS_ERRORS: true
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: |
          npm install
          npm install --save-dev typescript @types/react @types/node @types/react-dom

      - name: Build do projeto (Modo Permissivo)
        run: npx next build --no-lint
