name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Resolve o aviso de depreciação do Node 20

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Atualizado para a versão recomendada em 2026
          # Removi a linha do cache temporariamente para o erro sumir

      - name: Instalar dependências e tipos
        run: |
          npm install
          npm install --save-dev typescript @types/react @types/node
          
      - name: Build do projeto
        run: npm run build
